### ISSUE TITLE
In the settings add an achievements sections 

### ISSUE THREAD

**Issue by PratyushSingh07** [PratyushSingh07/cyclofit#11]
Achievement section will give badges to the user currently in the following scenarios : 

1. When he completes the first 10km on the bicycle
2. When he burns the first 10kcal 
3. When his cycling speed reaches 25kmph

**Comment by ritikaofc** [comment]
Please assign this issue to me.

**Comment by PratyushSingh07** [comment]
go ahead @ritikaofc
