### ISSUE TITLE
Add a menu to visualize data in forms other than the line chart

### ISSUE THREAD

**Issue by PratyushSingh07** [PratyushSingh07/cyclofit#13]
For the time being add a Pie Chart and Combined-Chart (bar- and linechart ). Add an option to switch between the charts and in the form a menu (three horizontal dots in top right corner) in the health fragment 

For reference in case of charts refer to https://github.com/PhilJay/MPAndroidChart

**Comment by PratyushSingh07** [comment]
keeping it open

**Comment by emzm17** [comment]
@PratyushSingh07 I have one query: do you want charts to be displayed in that viewpager box?

**Comment by PratyushSingh07** [comment]
> @PratyushSingh07 I have one query: do you want charts to be displayed in that viewpager box?

preferably , but if u have any other idea then I would love to hear them.

**Comment by princeraj-pr** [comment]
Hey @PratyushSingh07 assign it to me

**Comment by PratyushSingh07** [comment]
Sure @princeraj-pr
