### ISSUE TITLE
Remove the background grid and make the lines curve 

### ISSUE THREAD

**Issue by PratyushSingh07** [PratyushSingh07/cyclofit#2]
<img src="https://user-images.githubusercontent.com/90026952/205490218-4ff64999-57a9-4189-a922-d8eced6045bd.jpeg" height =600 >

**Comment by ritikaofc** [comment]
Hey, I'd like to work on this issue.

**Comment by PratyushSingh07** [comment]
> Hey, I'd like to work on this issue.

Sure, go ahead
