### ISSUE TITLE
Update: Support for Android version 14 (SDK version 34)

### ISSUE THREAD

**Issue by princeraj-pr** [PratyushSingh07/cyclofit#33]
The app does not support the latest Android version (only supporting Android version 12 and SDK version 32).

**Comment by princeraj-pr** [comment]
Hello @PratyushSingh07, Please review this issue and assign it to me under the CodePeak23 label.

**Comment by PratyushSingh07** [comment]
you can work on this issue @princeraj-pr . You have been awarded points for this issue as well as the merged PR

**Comment by PratyushSingh07** [comment]
any updates on this @princeraj-pr
