### ISSUE TITLE
Bug: In dark mode card view corners have thin white line borders

### ISSUE THREAD

**Issue by princeraj-pr** [PratyushSingh07/cyclofit#34]
In dark mode layout\home_fragment.xml MaterialCardView corners have thin white line borders

Screenshot
![screenshot](https://github.com/PratyushSingh07/cyclofit/assets/40030547/eb9d7cdf-623e-405c-8d62-00e6bfdbab9d)

Device info:
Phone: Realme X
Android version: 11

**Comment by PratyushSingh07** [comment]
Well we wanted it to be this way. So I will be closing this one
