### ISSUE TITLE
Bug: Leaderboard top user info text is not clearly visible when the dark mode is enabled

### ISSUE THREAD

**Issue by princeraj-pr** [PratyushSingh07/cyclofit#35]
The text on the leaderboard top user info(name, distance covered, and email) is not visible due to the light green background when the dark mode is enabled.

1. Go to profile
2. Click on theme
3. Select dark
4. Click confirm
5. Go to Leaderboard
6. See error

Screenshot
![Screenshot_2023-12-17-16-30-45-96_48d0ff434c8fef843eb6c6147ead4de5](https://github.com/PratyushSingh07/cyclofit/assets/40030547/52f1d33c-f58f-4bb9-b12e-92b75935913e)

Smartphone:
Device: Realme X
Android version: 11

**Comment by PratyushSingh07** [comment]
You can work on it @princeraj-pr
