### ISSUE TITLE
Add option to sort the leaderboard on the basis of distance covered 

### ISSUE THREAD

**Issue by PratyushSingh07** [PratyushSingh07/cyclofit#4]

**Comment by PratyushSingh07** [comment]
hey @Ohior , yeah this is a feature that we want to implement . You can go ahead with it

**Comment by Ohior** [comment]
Okay, I can do that

> hey @Ohior , yeah this is a feature that we want to implement . You can go ahead with it
> 
> To achieve this can you inflate a menu in the top right corner with options as sort->By name->By distance

Okay, I can do that

**Comment by Ohior** [comment]
should the distance be displayed from highest to lowest?

**Comment by Ohior** [comment]
I have created a merge request. Please check it out and keep me updated

**Comment by Ohior** [comment]
Hi @PratyushSingh07 I appreciate been part of something grand. I will love to be part of your future projects, please don't hesitate to contact me.
