### ISSUE TITLE
Feat: Collapsible toolbar on the Community page and Leaderboard page

### ISSUE THREAD

**Issue by princeraj-pr** [PratyushSingh07/cyclofit#41]
The collapsible toolbar provides more screen space to view community posts and leaderboard rankings.

**Comment by PratyushSingh07** [comment]
Can you give more insight on this issue of years? Such as the improvements it will bring and so on

**Comment by princeraj-pr** [comment]
A scrollable toolbar gives users more screen space to view content, and scrolling feels smooth.

YouTube has a scrollable toolbar

https://github.com/PratyushSingh07/cyclofit/assets/40030547/fb7741dd-7b22-412a-bfba-4b993bfa0674
