### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by PratyushSingh07** [PratyushSingh07/cyclofit#46]
There have been considerable changes in the UI of this app.  Its time to replace current images in the `README.md` with the latest ones. 

## Note
Replace the screenshots with their corresponding screens. For instance, if an image displays a graph, the most recent screenshot should also depict the screen that shows the graph

**Comment by princeraj-pr** [comment]
Assign me

**Comment by PratyushSingh07** [comment]
Go ahead!!
