### ISSUE TITLE
Add a feature to search in the leaderboard

### ISSUE THREAD

**Issue by PratyushSingh07** [PratyushSingh07/cyclofit#5]
Currently the search bar in the leaderboard fragment is a dummy . Make changes such that the whenever a name is entered if automatically comes up in the leaderboard

**Comment by Rohit-554** [comment]
I would like to work on this

**Comment by PratyushSingh07** [comment]
> I would like to work on this

go ahead

**Comment by Rohit-554** [comment]
Thanks ☺️

**Comment by Ohior** [comment]
there is no logic to the search box

**Comment by Rohit-554** [comment]
No just sorting based on the name and storing in a new list then passing that list to the adapter class

**Comment by Ohior** [comment]
> No just sorting based on the name and storing in a new list then passing that list to the adapter class

Oh, okay
